;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Datas/AbilitySystem/GameplayTags/DT_AuraGameplayTags.DT_AuraGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Vital.HealthPoint",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.ManaPoint",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.MaxHealthPoint",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.MaxManaPoint",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")

