;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Datas/AbilitySystem/GameplayTags/DT_AuraGameplayTags.DT_AuraGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Anim.CastFireBolt",NewTagName="Event.Montage.CastFireBolt")
+GameplayTagRedirects=(OldTagName="Event.Anim",NewTagName="Event.Montage")
+GameplayTagList=(Tag="Event.Montage.CastFireBolt",DevComment="Event in Montage to create FileBolt")

